language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem update bundler

# We only test the oldest and the newest ruby versions that we support. We
# do not test intermediate versions.
rvm:
  - 2.3.7
  - 2.5.1

# We only test living versions of rails, per the [rails maintenance
# policy](http://guides.rubyonrails.org/maintenance_policy.html)
gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x

matrix:
  fast_finish: true

# We want to use `sudo: false` because the container infrastructure is supposed
# to be faster, but Travis is having issues with containers lately ..
#
# > No output has been received in the last 10m0s
#
# .. and they recommend we use the VM infrastructure (`sudo: required`) in
# the meantime.
sudo: required
