addons:
  # rails 6 only supports PostgreSQL >= 9.3
  postgresql: "9.4"

language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - mysql -e 'create database authlogic;'
  - psql -c 'create database authlogic;' -U postgres

after_script:
  - bundle exec rake coveralls:push

env:
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

# We only test the oldest and the newest ruby versions that we support. We
# do not test intermediate versions.
rvm:
  - 2.4.9
  - 2.7.0

# We only test living versions of rails, per the [rails maintenance
# policy](http://guides.rubyonrails.org/maintenance_policy.html)
gemfile:
  - gemfiles/rails_5.2.rb
  - gemfiles/rails_6.0.rb
  - gemfiles/rails_6.1.rb

matrix:
  exclude:
    # rails 6 requires ruby >= 2.5.0
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.rb
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.1.rb
  fast_finish: true

services:
  - mysql
  - postgresql

# We want to use `sudo: false` because the container infrastructure is supposed
# to be faster, but Travis is having issues with containers lately ..
#
# > No output has been received in the last 10m0s
#
# .. and they recommend we use the VM infrastructure (`sudo: required`) in
# the meantime.
sudo: required
